name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check if package.json exists
        run: |
          if [ -f package.json ]; then
            echo "package.json found"
            cat package.json
          else
            echo "No package.json found - creating simple HTML deployment"
          fi

      - name: Install and Build (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm install
            npm run build
            echo "Built files:"
            ls -la dist/ || ls -la build/ || echo "No dist or build folder found"
          else
            echo "Skipping build step"
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/dist || ${{ github.workspace }}/build || ${{ github.workspace }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
